# Generated by Django 3.0.2 on 2020-02-13 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lovezyf', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='time',
        ),
    ]
